### ISSUE TITLE
Running with `prebuild --all`

### ISSUE THREAD

**Issue by mmckegg** [prebuild/prebuild-ci#8]
Is there a reason that this module specifically plucks out specific versions to build? I'm pretty confused about how it chooses which electron versions to build for, and how that relates to the version of node running in the env.

Would it be simpler if there was an option to make it run `prebuild --all`?

**Comment by juliangruber** [comment]
It's building mainly against the _current_ node version as you configure your CI environment to run your builds in multiple environments. The extra versions it's building against are for electron - there are some electron ABI versions that are _not_ available in node, so those wouldn't be picked up otherwise.

Does that make sense?

**Comment by mmckegg** [comment]
I think so. But won't those oddball electrons get built multiple times if you run in different node environments?

**Comment by juliangruber** [comment]
Yes they will be, but there's not really anything we can do against that afaik

**Comment by vweevers** [comment]
Maybe if you could specify some environment var in a build matrix, that defaults to false?

```yaml
- matrix:
  fast_finish: true
  include:
  - node_js: latest
    env:
      - PREBUILD_ODDBALL_ELECTRON=true
  - node_js: 6
  - node_js: 8
  - node_js: 9
```
